kind: pipeline
type: docker
name: build-and-push

steps:
- name: build
  image: docker:27
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build -t smokile/drone-test:${DRONE_BUILD_NUMBER} .
  - docker tag smokile/drone-test:${DRONE_BUILD_NUMBER} smokile/drone-test:latest

- name: push
  image: docker:27
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push smokile/drone-test:${DRONE_BUILD_NUMBER}
  - docker push smokile/drone-test:latest

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
